WasteMVC/Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WasteMVC.Data;
using WasteMVC.Models;
using Microsoft.Extensions.Logging;
using Microsoft.VisualStudio.Web.CodeGeneration;

namespace WasteMVC.Controllers
{
    public class PersonsController : Controller
    {
        private readonly UnitOfWork<SystemContext> _uow = null;

        public PersonsController(SystemContext _context)
        {
            _uow = new UnitOfWork<SystemContext>(_context);
        }

        // GET: Persons
        public async Task<IActionResult> Index(string sortOrder = "firstname_asc", string searchString = "")
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["FirstNameSortParm"] = sortOrder == "firstname_desc" ? "firstname_asc" : "firstname_desc";
            ViewData["LastNameSortParm"] = sortOrder == "lastname_desc" ? "lastname_asc" : "lastname_desc";
            ViewData["CurrentFilter"] = searchString;
            var _person = from p in _uow.GetRepository<Person>().Get()
                          select p;
            if (!String.IsNullOrEmpty(searchString))
            {
                _person = _person.Where(s => (s.FirstName.Contains(searchString) || s.LastName.Contains(searchString)));
            }
            switch (sortOrder)
            {
                case "firstname_asc":
                    _person = _person.OrderBy(p => p.FirstName);
                    break;
                case "firstname_desc":
                    _person = _person.OrderByDescending(p => p.FirstName);
                    break;
                case "lastname_asc":
                    _person = _person.OrderBy(p => p.LastName);
                    break;
                case "lastname_desc":
                    _person = _person.OrderByDescending(p => p.LastName);
                    break;
                default:
                    break;
            }
            return View(await _person.AsNoTracking().ToListAsync());
        }

        // GET: Persons/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Person _person = await _uow.GetRepository<Person>()
                                        .Get(p => p.Id == id)
                                        .Include(p => p.Business)
                                            .ThenInclude(p => p.Waste)
                                                .ThenInclude(wt => wt.WasteType)
                                        .SingleOrDefaultAsync();

            if (_person == null)
            {
                return NotFound();
            }

            return View(_person);
        }

        // GET: Persons/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Persons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,Id")] Person person)
        {
            if (ModelState.IsValid)
            {
                if (_uow.GetRepository<Person>().Add(person))
                {
                    await _uow.CommitAsync();
                    return RedirectToAction("Index");
                }
            }
            return View(person);
        }

        // GET: Persons/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            Person _person = await _uow.GetRepository<Person>()
                                        .FindAsync(x => x.Id == id);
            if (_person == null)
            {
                return NotFound();
            }
            return View(_person);
        }

        // POST: Persons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FirstName,LastName,Id")] Person _person)
        {
            if (id != _person.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (_uow.GetRepository<Person>().Update(_person))
                        await _uow.CommitAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(_person.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(_person);
        }

        // GET: Persons/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Person _person = await _uow.GetRepository<Person>().FindAsync(x => x.Id == id);

            if (_person == null)
            {
                return NotFound();
            }

            return View(_person);
        }

        // POST: Persons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var _person = await _uow.GetRepository<Person>().FindAsync(x => x.Id == id);
            if (_person != null)
            {
                if (_uow.GetRepository<Person>().Delete(id))
                    if (await _uow.CommitAsync() <= 0)

                        ModelState.AddModelError("", "Unable to save changes. " +
                                            "Try again, and if the problem persists, " +
                                            "see your system administrator.");
            }
            return RedirectToAction("Index");
        }

        private bool PersonExists(int id)
        {
            return _uow.GetRepository<Person>().Any(p => p.Id == id);
        }
    }
}

WasteMVC/Controllers/WastesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WasteMVC.Data;
using WasteMVC.Models;
using WasteMVC.Models.WastesView;
using System.Text;

namespace WasteMVC.Controllers
{
    public class WastesController : Controller
    {
        private readonly SystemContext _context = null;
        private readonly UnitOfWork<SystemContext> _uow = null;

        public WastesController(SystemContext context)
        {
            _context = context;
            _uow = new UnitOfWork<SystemContext>(context);
        }

        // GET: Wastes
        public async Task<IActionResult> Index(int? id, int? page, string sortOrder = "", string currentFilter = "")
        {
            var _viewModel = new WastesIndex(_context);

            if ((page == null) && (page.HasValue))
            {
                page = 1;
            }
            if (sortOrder == "")
            {
                sortOrder = "date_asc";
            }

            ViewBag.Page = page;
            ViewData["CurrentFilter"] = currentFilter;
            ViewData["CurrentSort"] = sortOrder;
            ViewData["DateSort"] = sortOrder == "date_asc" ? "date_desc" : "date_asc";
            ViewData["WasteTypeSort"] = sortOrder == "wt_asc" ? "wt_desc" : "wt_asc"; ;
            ViewData["WeightSort"] = sortOrder == "weight_asc" ? "weight_desc" : "weight_asc"; ;
            ViewData["CostSort"] = sortOrder == "cost_asc" ? "cost_desc" : "cost_asc"; ;
            ViewData["SalePriceSort"] = sortOrder == "sale_asc" ? "sale_desc" : "sale_asc";

            _viewModel.Filter(currentFilter);
            _viewModel.Sort(sortOrder);
            await _viewModel.CreateView(page, 7);

            if (id != null)
            {
                ViewData["PartnersID"] = id.Value;
                _viewModel.GetPartners(id.Value);
            }
            return View(_viewModel);
        }

        // GET: Wastes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var waste = await _uow.GetRepository<Waste>()
                .Get(w => w.Id == id)
                .Include(w => w.WasteType)
                .Include(w => w.Partners)
                    .ThenInclude(pt => pt.Person)
                .FirstOrDefaultAsync();

            if (waste == null)
            {
                return NotFound();
            }
            return View(waste);
        }

        // GET: Wastes/Create
        public IActionResult Create()
        {
            Waste _new_waste = new Waste();
            PopulateWasteTypesAndPersons(_new_waste, true);
            return View();
        }

        // POST: Wastes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DateTime,Weight,Cost,SalePrice,Id,WasteTypeId")] Waste waste, string[] selectecPartners, string[] id_persons, string[] values_Porcentaje)
        {
            waste.WasteType = _uow.GetRepository<WasteType>()
                                        .Get(wt => wt.Id == waste.WasteTypeId)
                                        .FirstOrDefault();
            //Asociando PersonId -> Porcentage
            Dictionary<int, double> valuesIdPorcentage = new Dictionary<int, double>();
            int i = 0;
            foreach (var item in id_persons)
            {
                int id = int.Parse(item);
                double porcentaje = double.Parse(values_Porcentaje[i++]) / 100.00;
                valuesIdPorcentage.Add(id, porcentaje);
            }
            waste.Partners = new HashSet<Partner>();
            Person _p;
            int _id = 0;
            double totalporcentage = 0.0;
            if (selectecPartners != null)
            {
                foreach (var item in selectecPartners)
                {
                    _id = int.Parse(item);
                    _p = _uow.GetRepository<Person>().Find(_id);
                    totalporcentage += valuesIdPorcentage[_id];
                    if (_p != null)
                    {
                        waste.Partners.Add(
                            new Partner
                            {
                                Person = _p,
                                Percentage = valuesIdPorcentage[_id],
                            });
                    }
                }
            }
            bool band = true;
            if (waste.Partners.Count <= 0)
            {
                band = false;
                ModelState.AddModelError("", "Error::Validadndo Cantidad de Socio." +
                                            "\nNo se puede guardar los cambios." +
                                            "\nDebe seleccionar al menos un socio.");
            }
            if (totalporcentage != 1.00)
            {
                band = false;
                string errorMessage = "Error::Validando la Participacion de los Socios." +
                                            " No se puede guardar los cambios." +
                                            " Total Participacion: " +
                                            totalporcentage.ToString("P2") + "," +
                                            " Falta: " +
                                            (1.00 - totalporcentage).ToString("P2");
                ModelState.AddModelError("", errorMessage);
            }
            if (ModelState.IsValid && band == true)
            {
                if (_uow.GetRepository<Waste>().Add(waste))
                {
                    int count = await _uow.CommitAsync();
                    if (count > 0)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Error::Creando El Desperdicio. No se puedo Guardar en la Base de Datos.");
                    }
                }
            }
            PopulateWasteTypesAndPersons(waste, true);
            return View(waste);
        }

        private void PopulateWasteTypesAndPersons(Waste waste, bool isNew)
        {
            var _wasteType = from wt in _uow.GetRepository<WasteType>().Get()
                             orderby wt.Description
                             select wt;
            ViewBag._wasteTypes = _wasteType.AsNoTracking().ToList();

            var _persons = from p in _uow.GetRepository<Person>().Get()
                           select p;
            if (isNew == false)
            {
                _persons = _persons.Include(p => p.Business);
            }
            _persons = _persons.OrderBy(p => p.LastName);
            ViewBag._persons = _persons.AsNoTracking().ToList();

            HashSet<AssignedPartnert> _partners = new HashSet<AssignedPartnert>();
            foreach (var item in _persons)
            {
                _partners.Add(
                    new AssignedPartnert
                    {
                        PersonId = item.Id,
                        FullName = item.FullName,
                        Assigned = item.BelongsToBusiness(waste.Id),
                        Procentage = item.BelongsToBusinessProcentage(waste.Id) * 100.00,
                    });
            }
            ViewBag._partners = _partners;
        }

        // GET: Wastes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Waste waste = await _uow.GetRepository<Waste>()
                                    .Get(w => w.Id == id)
                                    .Include(w => w.WasteType)
                                    .AsNoTracking()
                                    .FirstOrDefaultAsync();
            if (waste == null)
            {
                return NotFound();
            }
            PopulateWasteTypesAndPersons(waste, false);
            return View(waste);
        }

        // POST: Wastes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DateTime,Weight,Cost,SalePrice,Id,WasteTypeId")] Waste waste, string[] selectecPartners, string[] id_persons, string[] values_Porcentaje)
        {
            if (id != waste.Id)
            {
                return NotFound();
            }
            waste.WasteType = _uow.GetRepository<WasteType>().Find(waste.WasteTypeId);
            //Cargando Antiguos Valores de Socios
            HashSet<Partner> oldPartners = _uow.GetRepository<Waste>()
                                                .Get(w => w.Id == waste.Id)
                                                .Include(w => w.Partners)
                                                .AsNoTracking()
                                                .FirstOrDefault()
                                                .Partners;
            waste.Partners = new HashSet<Partner>();
            double totalporcentage = 0.0;
            if (selectecPartners != null)
            {
                //Asociando PersonId -> Porcentage
                Dictionary<int, double> valuesIdPorcentage = new Dictionary<int, double>();
                int i = 0;
                int personId = 0;
                foreach (var item in id_persons)
                {
                    personId = int.Parse(item);

WasteMVC/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WasteMVC</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand"
           asp-controller="Home"
           asp-action="Index">
            Sistema
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link"
                       asp-area=""
                       asp-action="Index"
                       asp-controller="Wastes"
                       asp-route-sortOrder="date_asc"
                       asp-route-page="1">
                        Desperdicios
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       asp-area=""
                       asp-action="Index"
                       asp-controller="WasteTypes"
                       asp-route-sortOrder="date_asc"
                       asp-route-page="1">
                        Tipos de Desperdicios
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       asp-area=""
                       asp-controller="Persons"
                       asp-action="Index">
                        Personas
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <br />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - WasteMVC</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
                asp-fallback-src="~/lib/popper.js/dist/popper.js"
                integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
                crossorigin="anonymous">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

WasteMVC/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Solution by Collection Of Bovine By-Products And Chickens</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand"
           asp-controller="Home"
           asp-action="Index">
            Sistema
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link"
                       asp-area=""
                       asp-action="Index"
                       asp-controller="Wastes"
                       asp-route-sortOrder="date_asc"
                       asp-route-page="1">
                        Desperdicios
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       asp-area=""
                       asp-action="Index"
                       asp-controller="WasteTypes"
                       asp-route-sortOrder="date_asc"
                       asp-route-page="1">
                        Tipos de Desperdicios
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       asp-area=""
                       asp-controller="Persons"
                       asp-action="Index">
                        Personas
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       asp-area=""
                       asp-controller="Home"
                       asp-action="About">
                        About
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <br />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Solution by Collection Of Bovine By-Products And Chickens</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="~/lib/popper.js/dist/popper.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>