WasteMVC/Controllers/PartnersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WasteMVC.Data;
using WasteMVC.Models;

namespace WasteMVC.Controllers
{
    public class PartnersController : Controller
    {
        private readonly SystemContext _context;

        public PartnersController(SystemContext context)
        {
            _context = context;    
        }

        // GET: Partners
        public async Task<IActionResult> Index()
        {
            return View(await _context.Partners.ToListAsync());
        }

        // GET: Partners/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var partner = await _context.Partners
                .SingleOrDefaultAsync(m => m.Id == id);
            if (partner == null)
            {
                return NotFound();
            }

            return View(partner);
        }

        // GET: Partners/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Partners/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Percentage,Id")] Partner partner)
        {
            if (ModelState.IsValid)
            {
                _context.Add(partner);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(partner);
        }

        // GET: Partners/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var partner = await _context.Partners.SingleOrDefaultAsync(m => m.Id == id);
            if (partner == null)
            {
                return NotFound();
            }
            return View(partner);
        }

        // POST: Partners/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Percentage,Id")] Partner partner)
        {
            if (id != partner.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(partner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PartnerExists(partner.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(partner);
        }

        // GET: Partners/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var partner = await _context.Partners
                .SingleOrDefaultAsync(m => m.Id == id);
            if (partner == null)
            {
                return NotFound();
            }

            return View(partner);
        }

        // POST: Partners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var partner = await _context.Partners.SingleOrDefaultAsync(m => m.Id == id);
            _context.Partners.Remove(partner);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool PartnerExists(int id)
        {
            return _context.Partners.Any(e => e.Id == id);
        }
    }
}

WasteMVC/Controllers/WastesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WasteMVC.Data;
using WasteMVC.Models;
using WasteMVC.Models.WastesView;
using System.Text;

namespace WasteMVC.Controllers
{
    public class WastesController : Controller
    {
        private readonly SystemContext _context = null;
        private readonly UnitOfWork<SystemContext> _uow = null;

        public WastesController(SystemContext context)
        {
            _context = context;
            _uow = new UnitOfWork<SystemContext>(context);
        }

        // GET: Wastes
        public async Task<IActionResult> Index(int? id, int? page, string sortOrder = "", string currentFilter = "")
        {
            var _viewModel = new WastesIndex(_context);

            if ((page == null) && (page.HasValue))
            {
                page = 1;
            }
            if (sortOrder == "")
            {
                sortOrder = "date_asc";
            }

            ViewBag.Page = page;
            ViewData["CurrentFilter"] = currentFilter;
            ViewData["CurrentSort"] = sortOrder;
            ViewData["DateSort"] = sortOrder == "date_asc" ? "date_desc" : "date_asc";
            ViewData["WasteTypeSort"] = sortOrder == "wt_asc" ? "wt_desc" : "wt_asc"; ;
            ViewData["WeightSort"] = sortOrder == "weight_asc" ? "weight_desc" : "weight_asc"; ;
            ViewData["CostSort"] = sortOrder == "cost_asc" ? "cost_desc" : "cost_asc"; ;
            ViewData["SalePriceSort"] = sortOrder == "sale_asc" ? "sale_desc" : "sale_asc";

            _viewModel.Filter(currentFilter);
            _viewModel.Sort(sortOrder);
            await _viewModel.CreateView(page, 7);

            if (id != null)
            {
                ViewData["PartnersID"] = id.Value;
                _viewModel.GetPartners(id.Value);
            }
            return View(_viewModel);
        }

        // GET: Wastes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var waste = await _uow.GetRepository<Waste>()
                .Get(w => w.Id == id)
                .Include(w => w.WasteType)
                .Include(w => w.Partners)
                    .ThenInclude(pt => pt.Person)
                .FirstOrDefaultAsync();

            if (waste == null)
            {
                return NotFound();
            }
            return View(waste);
        }

        // GET: Wastes/Create
        public IActionResult Create()
        {
            Waste _new_waste = new Waste();
            PopulateWasteTypesAndPersons(_new_waste, true);
            return View();
        }

        // POST: Wastes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DateTime,Weight,Cost,SalePrice,Id,WasteTypeId")] Waste waste, string[] selectecPartners, string[] id_persons, string[] values_Porcentaje)
        {
            waste.WasteType = _uow.GetRepository<WasteType>()
                                        .Get(wt => wt.Id == waste.WasteTypeId)
                                        .FirstOrDefault();
            //Asociando PersonId -> Porcentage
            Dictionary<int, double> valuesIdPorcentage = new Dictionary<int, double>();
            int i = 0;
            foreach (var item in id_persons)
            {
                int id = int.Parse(item);
                double porcentaje = double.Parse(values_Porcentaje[i++]) / 100.00;
                valuesIdPorcentage.Add(id, porcentaje);
            }
            waste.Partners = new HashSet<Partner>();
            Person _p;
            int _id = 0;
            double totalporcentage = 0.0;
            if (selectecPartners != null)
            {
                foreach (var item in selectecPartners)
                {
                    _id = int.Parse(item);
                    _p = _uow.GetRepository<Person>().Find(_id);
                    totalporcentage += valuesIdPorcentage[_id];
                    if (_p != null)
                    {
                        waste.Partners.Add(
                            new Partner
                            {
                                Person = _p,
                                Percentage = valuesIdPorcentage[_id],
                            });
                    }
                }
            }
            bool band = true;
            if (waste.Partners.Count <= 0)
            {
                band = false;
                ModelState.AddModelError("", "Error::Validadndo Cantidad de Socio." +
                                            "\nNo se puede guardar los cambios." +
                                            "\nDebe seleccionar al menos un socio.");
            }
            if (totalporcentage != 1.00)
            {
                band = false;
                string errorMessage = "Error::Validando la Participacion de los Socios." +
                                            " No se puede guardar los cambios." +
                                            " Total Participacion: " +
                                            totalporcentage.ToString("P2") + "," +
                                            " Falta: " +
                                            (1.00 - totalporcentage).ToString("P2");
                ModelState.AddModelError("", errorMessage);
            }
            if (ModelState.IsValid && band == true)
            {
                if (_uow.GetRepository<Waste>().Add(waste))
                {
                    int count = await _uow.CommitAsync();
                    if (count > 0)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Error::Creando El Desperdicio. No se puedo Guardar en la Base de Datos.");
                    }
                }
            }
            PopulateWasteTypesAndPersons(waste, true);
            return View(waste);
        }

        private void PopulateWasteTypesAndPersons(Waste waste, bool isNew)
        {
            var _wasteType = from wt in _uow.GetRepository<WasteType>().Get()
                             orderby wt.Description
                             select wt;
            ViewBag._wasteTypes = _wasteType.AsNoTracking().ToList();

            var _persons = from p in _uow.GetRepository<Person>().Get()
                           select p;
            if (isNew == false)
            {
                _persons = _persons.Include(p => p.Business);
            }
            _persons = _persons.OrderBy(p => p.LastName);
            ViewBag._persons = _persons.AsNoTracking().ToList();

            HashSet<AssignedPartnert> _partners = new HashSet<AssignedPartnert>();
            foreach (var item in _persons)
            {
                _partners.Add(
                    new AssignedPartnert
                    {
                        PersonId = item.Id,
                        FullName = item.FullName,
                        Assigned = item.BelongsToBusiness(waste.Id),
                        Procentage = item.BelongsToBusinessProcentage(waste.Id) * 100.00,
                    });
            }
            ViewBag._partners = _partners;
        }

        // GET: Wastes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Waste waste = await _uow.GetRepository<Waste>()
                                    .Get(w => w.Id == id)
                                    .Include(w => w.WasteType)
                                    .AsNoTracking()
                                    .FirstOrDefaultAsync();
            if (waste == null)
            {
                return NotFound();
            }
            PopulateWasteTypesAndPersons(waste, false);
            return View(waste);
        }

        // POST: Wastes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DateTime,Weight,Cost,SalePrice,Id,WasteTypeId")] Waste waste, string[] selectecPartners, string[] id_persons, string[] values_Porcentaje)
        {
            if (id != waste.Id)
            {
                return NotFound();
            }
            waste.WasteType = _uow.GetRepository<WasteType>().Find(waste.WasteTypeId);
            //Cargando Antiguos Valores de Socios
            HashSet<Partner> oldPartners = _uow.GetRepository<Waste>()
                                                .Get(w => w.Id == waste.Id)
                                                .Include(w => w.Partners)
                                                .AsNoTracking()
                                                .FirstOrDefault()
                                                .Partners;
            waste.Partners = new HashSet<Partner>();
            double totalporcentage = 0.0;
            if (selectecPartners != null)
            {
                //Asociando PersonId -> Porcentage
                Dictionary<int, double> valuesIdPorcentage = new Dictionary<int, double>();
                int i = 0;
                int personId = 0;
                foreach (var item in id_persons)
                {
                    personId = int.Parse(item);

WasteMVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}


<canvas id="canvas" width="700" height="500"></canvas>

<script>
    let canvas = document.getElementById('canvas');
    let ctx = canvas.getContext('2d');
    let sun = {
        x: canvas.width / 2,
        y: canvas.height / 2,
        radius: 40,
        color: 'yellow',
        draw: function () {
            ctx.beginPath();
            ctx.arc(this.x, this.y, this.radius, 0, Math.PI * 2, true);
            ctx.closePath();
            ctx.fillStyle = this.color;
            ctx.fill();

            ctx.beginPath();
            //ctx.arc(this.x, this.y, earth.hypotenuse, 0, Math.PI * 2, false); // Earth orbit Circular
            ctx.ellipse(this.x + 30, this.y, earth.hypotenuse, earth.hypotenuse / 1.5, 0, 0, 2 * Math.PI, false); // Earth Elliptical Orbit
            ctx.closePath();
            ctx.stroke();

        }
    }

    let earth = {
        x: 0,
        y: 0,
        angle: 0,
        hypotenuse: 200,
        radius: 20,
        color: 'blue',
        draw: function () {
            ctx.beginPath();
            ctx.arc(this.x, this.y, this.radius, 0, Math.PI * 2, true);
            ctx.closePath();
            ctx.fillStyle = this.color;
            ctx.fill();

            ctx.beginPath();
            ctx.arc(this.x, this.y, moon.hypotenuse, 0, Math.PI * 2, false); // Moon orbit
            ctx.closePath();
            ctx.stroke();

        },
        translate: function () {
            this.angle += 0.1;
            this.x = sun.x + 30 + this.hypotenuse * Math.cos(this.angle * (Math.PI / 180));
            this.y = sun.y + this.hypotenuse / 1.5 * Math.sin(this.angle * (Math.PI / 180));
        }
    }

    let moon = {
        x: 0,
        y: 0,
        angle: 0,
        hypotenuse: 50,
        radius: 10,
        color: 'black',
        draw: function () {

            ctx.beginPath();
            ctx.arc(this.x, this.y, this.radius, 0, Math.PI * 2, true);
            ctx.closePath();
            ctx.fillStyle = this.color;
            ctx.fill();
        },
        translate: function () {
            this.angle += 1;
            this.x = earth.x + this.hypotenuse * Math.cos(this.angle * (Math.PI / 180));
            this.y = earth.y + this.hypotenuse * Math.sin(this.angle * (Math.PI / 180));
        }
    }

    function draw() {
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        earth.translate();
        moon.translate();
        sun.draw();
        earth.draw();
        moon.draw();
    }
    setInterval(draw, 50)
</script>

WasteMVC/Views/Home/Details.cshtml
@model WasteMVC.Models.HomeView.HomeDetailsView
@{
    ViewData["Title"] = "Details";
}
<h3>Desperdicio</h3>
<h5>Dia: @Model.DateTime.ToString("dd/MM/yyy")</h5>
@if (Model.WasteType != string.Empty)
{
    <h5>Tipo: @Model.WasteType</h5>
}
<hr />
<table class="table">
    <thead>
        <tr>
            <th>
                Fecha
            </th>
            <th>
                Tipo de Desperdicio
            </th>
            <th>
                Costo
            </th>
            <th>
                Precio de Compra
            </th>
            <th>
                Precio de Venta
            </th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.View != null)
        {
            @foreach (var item1 in Model.View)
            {
                <tr>
                    <td>
                        @item1.DateTime.ToString("dd/MM/yyyy")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item1.WasteType.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item1.Weight)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item1.Cost)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item1.SalePrice)
                    </td>
                    <td>
                        <a asp-controller="Home"
                           asp-action="Details"
                           asp-route-day="@ViewData["Day"]" 
                           asp-route-wasteType="@ViewData["WasteType"]"
                           asp-route-page="@(Model.View.PageIndex)"
                           asp-route-partnersID="@item1.Id">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        </a> |
                        <a asp-controller="Wastes"
                           asp-action="Edit"
                           asp-route-id="@item1.Id">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a> |
                        <a asp-controller="Wastes"
                           asp-action="Details"
                           asp-route-id="@item1.Id">
                            <span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span>
                        </a> |
                        <a asp-controller="Wastes"
                           asp-action="Delete"
                           asp-route-id="@item1.Id">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>
                    </td>
                </tr>
                @if (Model.Partners != null && ViewBag.PartnersID == item1.Id)
                {
                    @foreach (var item2 in Model.Partners)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item2.Person.FirstName)</td>
                            <td>@Html.DisplayFor(modelItem => item2.Person.LastName)</td>
                            <td>@Html.DisplayFor(modelItem => item2.Percentage)</td>
                            <td class="text-center">
                                <a asp-controller="Partners" asp-action="Edit" asp-route-id="@item2.Id"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a> |
                                <a asp-controller="Partners" asp-action="Details" asp-route-id="@item2.Id"><span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span></a> |
                                <a asp-controller="Partners" asp-action="Delete" asp-route-id="@item2.Id"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                            </td>
                        </tr>
                    }
                }
            }
        }
    </tbody>
</table>
<hr />

@if (Model.View != null)
{
    var prevDisabled = !Model.View.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.View.HasNextPage ? "disabled" : "";
    <div class="center-block text-center">
        <a asp-controller="Home"
           asp-action="Details"
           asp-route-day="@ViewData["Day"]"
           asp-route-wasteType="@ViewData["WasteType"]"
           asp-route-page="@(Model.View.PageIndex - 1)"
           asp-route-id=""
           class="btn btn-default @prevDisabled">
            <
        </a>
        @for (int i = 1; i <= Model.View.TotalPages; i++)
        {
            if (((i - 5) < ViewBag.Page) && (ViewBag.Page < (i + 5)))
            {
                <a asp-controller="Home"
                   asp-action="Details"
                   asp-route-day="@ViewData["Day"]"
                   asp-route-wasteType="@ViewData["WasteType"]"
                   asp-route-page="@(i)"
                   asp-route-id=""
                   class="btn btn-default">
                    @i
                </a>
            }
            else if (i % 5 == 0 || i == 1)
            {
                <a asp-controller="Home"
                   asp-action="Details"
                   asp-route-page="@(i)"
                   asp-route-id=""
                   class="btn btn-default">
                    @i
                </a>
            }
        }

        <a asp-controller="Home"
           asp-action="Details"
           asp-route-day="@ViewData["Day"]" 
           asp-route-wasteType="@ViewData["WasteType"]"
           asp-route-page="@(Model.View.PageIndex + 1)"
           asp-route-id=""
           class="btn btn-default @nextDisabled">
            >
        </a>
    </div>
}

WasteMVC/Views/Home/Edit.cshtml
@model WasteMVC.Models.HomeView.HomeEditView

@{
    ViewData["Title"] = "Edit";
}

<h3>Desperdicio</h3>
<h5>Dia: @Model.DateTime.ToString("dd/MM/yyy")</h5>
@if (Model.WasteType != string.Empty)
{
    <h5>Tipo: @Model.WasteType</h5>
}
<hr />
<table class="table">
    <thead>
        <tr>
            <th>
                Fecha
            </th>
            <th>
                Tipo de Desperdicio
            </th>
            <th>
                Costo
            </th>
            <th>
                Precio de Compra
            </th>
            <th>
                Precio de Venta
            </th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.View != null)
        {
            @foreach (var item1 in Model.View)
            {
                <tr>
                    <td>
                        @item1.DateTime.ToString("dd/MM/yyyy")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item1.WasteType.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item1.Weight)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item1.Cost)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item1.SalePrice)
                    </td>
                    <td>
                        <a asp-controller="Home"
                           asp-action="Edit"
                           asp-route-day="@ViewData["Day"]"
                           asp-route-wasteType="@ViewData["WasteType"]"
                           asp-route-page="@(Model.View.PageIndex)"
                           asp-route-partnersID="@item1.Id">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        </a> |
                        <a asp-controller="Wastes"
                           asp-action="Edit"
                           asp-route-id="@item1.Id">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a> |
                        <a asp-controller="Wastes"
                           asp-action="Details"
                           asp-route-id="@item1.Id">
                            <span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span>
                        </a> |
                        <a asp-controller="Wastes"
                           asp-action="Delete"
                           asp-route-id="@item1.Id">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>
                    </td>
                </tr>
                @if (Model.Partners != null && ViewBag.PartnersID == item1.Id)
                {
                    @foreach (var item2 in Model.Partners)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item2.Person.FirstName)</td>
                            <td>@Html.DisplayFor(modelItem => item2.Person.LastName)</td>
                            <td>@Html.DisplayFor(modelItem => item2.Percentage)</td>
                            <td class="text-center">
                                <a asp-controller="Partners" asp-action="Edit" asp-route-id="@item2.Id"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a> |
                                <a asp-controller="Partners" asp-action="Details" asp-route-id="@item2.Id"><span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span></a> |
                                <a asp-controller="Partners" asp-action="Delete" asp-route-id="@item2.Id"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                            </td>
                        </tr>
                    }
                }
            }
        }
    </tbody>
</table>
<hr />
<form asp-action="Edit">
    @if (Model.View != null)
    {
        @foreach (var item1 in Model.View)
        {
            <input type="hidden" name="wastesID" value="@item1.Id" class="form-control" />
        }
    }
    <input type="hidden" name="day" value="@Model.DateTime.ToString("dd/MM/yyy")" class="form-control" />
    <div class="form-horizontal">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Cost2" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Cost2" class="form-control" />
                <span asp-validation-for="Cost2" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SalePrice2" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SalePrice2" class="form-control" />
                <span asp-validation-for="SalePrice2" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Decrease" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Decrease" class="form-control" />
                <span asp-validation-for="Decrease" class="text-danger"></span>
            </div>
        </div>
        <input type="hidden" asp-for="DateTime" />
        <input type="hidden" asp-for="WasteType" />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a asp-controller="Home"
                   asp-action="Index"
                   asp-route-day="@ViewData["Day"]"
                   asp-route-page="1"
                   class="btn btn-default">
                    <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                </a>
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>
<hr />

@if (Model.View != null)
{

    var prevDisabled = !Model.View.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.View.HasNextPage ? "disabled" : "";

    <div class="center-block text-center">
        <a asp-controller="Home"
           asp-action="Edit"
           asp-route-day="@ViewData["Day"]"
           asp-route-wasteType="@ViewData["WasteType"]"
           asp-route-page="@(Model.View.PageIndex - 1)"
           asp-route-id=""
           class="btn btn-default @prevDisabled">
            <
        </a>
        @for (int i = 1; i <= Model.View.TotalPages; i++)
        {
            if (((i - 5) < ViewBag.Page) && (ViewBag.Page < (i + 5)))
            {
                <a asp-controller="Home"
                   asp-action="Edit"
                   asp-route-day="@ViewData["Day"]"
                   asp-route-wasteType="@ViewData["WasteType"]"
                   asp-route-page="@(i)"
                   asp-route-id=""
                   class="btn btn-default">
                    @i
                </a>
            }
            else if (i % 5 == 0 || i == 1)
            {
                <a asp-controller="Home"
                   asp-action="Edit"
                   asp-route-page="@(i)"
                   asp-route-id=""
                   class="btn btn-default">
                    @i
                </a>
            }
        }

        <a asp-controller="Home"
           asp-action="Edit"
           asp-route-day="@ViewData["Day"]"
           asp-route-wasteType="@ViewData["WasteType"]"
           asp-route-page="@(Model.View.PageIndex + 1)"
           asp-route-id=""
           class="btn btn-default @nextDisabled">
            >
        </a>
    </div>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}